module.exports.WEEK_DAYS = {
  MONDAY: "MON",
  TUESDAY: "TUE",
  WEDNESDAY: "WED",
  THURSDAY: "THU",
  FRIDAY: "FRI",
  SATURDAY: "SAT",
  SUNDAY: "SUN",
};
module.exports.MONTHS = {
  JANUARY: "JAN",
  FEBRUARY: "FEB",
  MARCH: "MAR",
  APRIL: "APR",
  MAY: "MAY",
  JUNE: "JUN",
  JULY: "JUL",
  AUGUST: "AUG",
  SEPTEMBER: "SEP",
  OCTOBER: "OCT",
  NOVEMBER: "NOV",
  DECEMBER: "DEC",
};
module.exports.INDEX_INDICES = {
  MIDCPNIFTY: 0,
  BANKEX: 1,
  FINNIFTY: 2,
  BANKNIFTY: 3,
  NIFTY: 4,
  SENSEX: 5,
};
module.exports.DAYS_OF_WEEK = [
  "SUN",
  "MON",
  "TUE",
  "WED",
  "THUR",
  "FRI",
  "SAT",
];
module.exports.MONTHS_OF_YEAR = [
  "JAN",
  "FEB",
  "MAR",
  "APR",
  "MAY",
  "JUN",
  "JUL",
  "AUG",
  "SEP",
  "OCT",
  "NOV",
  "DEC",
];
module.exports.INDEX_DETAILS = [
  {
    name: "NIFTY MID SELECT",
    key: "MIDCPNIFTY",
    id: "26074",
    exch: "NSE",
    optExch: "NFO",
    lotSize: 75,
    lotDiff: 25,
    defExp: this.WEEK_DAYS.MONDAY,
    algos: {
      ATM_SELL_1: "",
      ATM_SELL_2: "",
      ATM_SELL_3: "",
      OTM_SELL: "",
      BUY: "",
    },
  },
  {
    name: "BANKEX",
    key: "BANKEX",
    id: "12",
    exch: "BSE",
    optExch: "BFO",
    lotSize: 15,
    lotDiff: 100,
    defExp: this.WEEK_DAYS.MONDAY,
    algos: {
      ATM_SELL_1: "",
      ATM_SELL_2: "",
      ATM_SELL_3: "",
      OTM_SELL: "",
      BUY: "",
    },
  },
  {
    name: "Nifty Fin Service",
    key: "FINNIFTY",
    id: "26037",
    exch: "NSE",
    optExch: "NFO",
    lotSize: 40,
    lotDiff: 50,
    defExp: this.WEEK_DAYS.TUESDAY,
    algos: {
      ATM_SELL_1: "66498309aa0ce4729c7df073",
      ATM_SELL_2: "6649830029476158dfdbfe2b",
      ATM_SELL_3: "6649820eaa0ce4729c7df063",
      OTM_SELL: "6649820eaa0ce4729c7df05f",
      BUY: "6649820eaa0ce4729c7df061",
    },
  },
  {
    name: "Nifty Bank",
    key: "BANKNIFTY",
    id: "26009",
    exch: "NSE",
    optExch: "NFO",
    lotSize: 15,
    lotDiff: 100,
    defExp: this.WEEK_DAYS.WEDNESDAY,
    algos: {
      ATM_SELL_1: "6649efc229476158dfdc0ab9",
      ATM_SELL_2: "6649efc229476158dfdc0aba",
      ATM_SELL_3: "6649efc229476158dfdc0abd",
      OTM_SELL: "6649820eaa0ce4729c7df061",
      BUY: "6649efc229476158dfdc0abe",
    },
  },
  {
    name: "Nifty 50",
    key: "NIFTY",
    id: "26000",
    exch: "NSE",
    optExch: "NFO",
    lotSize: 25,
    lotDiff: 50,
    defExp: this.WEEK_DAYS.THURSDAY,
    algos: {
      ATM_SELL_1: "",
      ATM_SELL_2: "",
      ATM_SELL_3: "",
      OTM_SELL: "",
      BUY: "",
    },
  },
  {
    name: "SENSEX",
    key: "SENSEX",
    id: "1",
    exch: "BSE",
    optExch: "BFO",
    lotSize: 10,
    lotDiff: 100,
    defExp: this.WEEK_DAYS.FRIDAY,
    algos: {
      ATM_SELL_1: "",
      ATM_SELL_2: "",
      ATM_SELL_3: "",
      OTM_SELL: "",
      BUY: "",
    },
  },
];
